App/urls.py
from django.urls import path

from .views import *

app_name = 'main'
urlpatterns = [
    path('', home_view, name='home'),
    path('inbox/', inbox_view, name='inbox'),
    path('send_message', send_message_view, name='send_message'),
    path('del_message/<int:id>/', delete_message_view, name='del_message'),
    path('customer/<int:id>/', customer_detail_view, name='customer'),
    path('mark_message/', mark_message, name='mark_message'),
    path('email', email, name='email'),
    path('auto_logout/', auto_logout_user, name='auto_logout'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('logout/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ROUTES TO SHOW ERROR PAGES
handler500 = 'App.views.error_500'
handler404  = 'App.views.error_404'

App/models.py
from django.db import models
from django.utils.html import format_html


class Customer(models.Model):
    STATUS = (
        ('Pending', 'pending'),
        ('Read', 'read'),
    )
    name = models.CharField('Nombre', max_length=50)
    phone = models.CharField('Teléfono', max_length=20)
    email = models.EmailField('Email', max_length=254)
    subject = models.CharField('Asunto', max_length=20)
    message = models.TextField('Mensaje')
    file = models.FileField('Archivos')
    created_at = models.DateTimeField('Enviado', auto_now=False, auto_now_add=True)
    status = models.CharField('Estado', max_length=50, choices=STATUS)

    # CONTROL READ/UNREAD MESSAGE ON ADMIN.PY
    def situation(self):
        if self.status == 'Read':
            return format_html('<span style="color:black">{0}</span>', self.status)
        else:
            return format_html('<span style="color:red">{0}</span>', self.status)
    situation.allow_tags = True

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Inbox'

App/forms.py
from django import forms

from .models import Customer


class CustomerForm(forms.ModelForm):
    file = forms.FileField(required=False)

    class Meta:
        model = Customer
        fields = '__all__'


class EmailForm(forms.Form):
    email = forms.EmailField()
    cc = forms.EmailField(required=False)
    subject = forms.CharField(max_length=100)

    # Permitir la subida de multiples archivos
    attach = forms.FileField(
        required=False,
        widget= forms.ClearableFileInput(
            attrs= {
                'multiple': True
            }
        )
    )
    message = forms.CharField(widget = forms.Textarea)
    customer_status = forms.HiddenInput()
    customer_id = forms.HiddenInput()

App/views.py
from datetime import datetime

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.cache import cache_control  # Destruye la sesisón después de hacer logout
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator  # Paginación
from django.db.models import Q   # Codiciones en los filtros (OR)
from django.core.mail import EmailMessage  # Envío correos
from django.contrib.auth import logout  # Auto logout

from .models import Customer
from .forms import CustomerForm, EmailForm


# ====================== FRONTEND VIEWS ================================
def home_view(request):
    return render(request, 'home.html', {})

# FUNCTION TO SEND A MESSAGE
def send_message_view(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            messages.success(request, 'Mensaje enviado !')
            return HttpResponseRedirect('/')
    else:
        form = CustomerForm()
        return render(request, 'home.html', {'form': form})


# ====================== BACKEND VIEWS ================================
@login_required(login_url='login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def inbox_view(request):
    customer_list = []
    if 'q' in request.GET:
        q = request.GET['q']
        customer_list = Customer.objects.filter(
            Q(name__icontains=q) | Q(phone__icontains=q) |
            Q(email__icontains=q) | Q(subject__icontains=q) |
            Q(status__icontains=q) | Q(message__icontains=q) 
        ).order_by('-created_at')
    else:
        customer_list = Customer.objects.all().order_by('-created_at')

    # Pagination
    paginator = Paginator(customer_list, 6)
    page = request.GET.get('page')
    all_customers = paginator.get_page(page)

    date_current = datetime.now().date()
    print(date_current)
    context = {
        'customers': all_customers,
        'total': Customer.objects.all().count(),
        'read': Customer.objects.filter(status='Read'),
        'pending': Customer.objects.filter(status='Pending'),
        'today': Customer.objects.filter(created_at__gt=date_current)
    }

    return render(request, 'inbox.html', context)


@login_required(login_url='login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delete_message_view(request, id):
    customer = Customer.objects.get(id=id)
    customer.delete()
    messages.success(request, 'Registro Eliminado !')
    return HttpResponseRedirect('/inbox')


@login_required(login_url='login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def customer_detail_view(request, id):
    customer = Customer.objects.get(id=id)

    if customer is not None:
        return render(request, 'customer.html', {'customer': customer})


@login_required(login_url='login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def mark_message(request):
    if request.method == 'POST':
        customer = Customer.objects.get(id=request.POST.get('id'))
        print(customer)
        if customer is not None:
            customer.status = request.POST.get('status')
            customer.save()
            messages.success(request, 'Mensaje marcado como leído !')
            return HttpResponseRedirect('/inbox')



# RESPONSE A MESSAGE AND SEND EMAIL VIEW
@login_required(login_url='login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def email(request):
    if request.method == 'POST':
        form = EmailForm(request.POST, request.FILES)
        company = 'Reply Consultoring'

        # lines add to resolve the change status message
        customer_id = request.POST.get('customer_id')  #
        customer_status = request.POST.get('status')
        customer = Customer.objects.get(id=customer_id)

        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']
            cc = form.cleaned_data['cc']
            files = request.FILES.getlist('attach')

            mail = EmailMessage(subject, message, company, [email], [cc])

            for file in files:
                mail.attach(file.name, file.read(), file.content_type)
            mail.send()

            # lines add to resolve the change status message
            if customer_status == 'Pending':
                customer.status = 'Read'
                customer.save()

            messages.success(request, 'Respuesta Enviada correctamente!')
            return HttpResponseRedirect('/inbox')
    else:
        form = EmailForm()
        return render(request, {'form', form})


@login_required(login_url='login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def auto_logout_user(request):
    logout(request)
    request.user = None
    messages.info(request, '.')  # el mensaje se pasa en el front. se pone . porque el argumento no puede ser vacío
    return HttpResponseRedirect('/')


# =================================  ERROR PAGES ===============================
def error_500(request):
    return render(request, '500.html')


def error_404(request, exception):
    return render(request, '404.html')

App/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=Inbox System, initial-scale=1.0">
    <title>{% block title %}Inbox . Home{% endblock title %}</title>

    <!-- Bootstrap cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">   
    
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <!-- Boxi Icons -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Logo -->
    <link rel="shortcut icon" href="{% static 'images/logo.ico' %}">

    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

     <!-- Jquery -->
     <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
</head>
<body>

    <!-- Wrraper -->
    <div class="wrapper">
        {% block bg-image %}
        <style>
            body {
                background-image: url('/static/images/bg.jpg');
                background-position: center opx;
                background-repeat: no-repeat;
                background-attachment: fixed;
                background-size: cover;
            }
        </style>
        {% endblock bg-image %}
            
        <!-- Block Header -->
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="col-sm">
                    {% if user.is_authenticated %}
                    <a href="{% url 'main:inbox' %}" class="navbar-brand flex-grow-1" style="color: #fff; margin-left: 25px;">
                        <i class='bx bx-send bx-rotate-270 align-middle' style="color: #8abaae; font-size: 24px;"></i>&nbsp;
                        <span class="align-middle">Inbox</span>
                    </a>
                    {% else %}
                    <a href="{% url 'main:home' %}" class="navbar-brand flex-grow-1" style="color: #fff; margin-left: 25px;">
                        <i class='bx bx-send bx-rotate-270 align-middle' style="color: #8abaae; font-size: 24px;"></i>&nbsp;
                        <span class="align-middle">Consultoring</span>
                    </a>
                    {% endif %}
                </div>

                <!-- section data and time -->
                {% block datetime %}{% endblock datetime %}

                <!-- column menu -->
                <div class="col-sm">
                    <a href="" class="navbar-brand flex-grow-1" id="btn-nav" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                        <i class='bx bx-menu'></i>
                    </a>
                </div>
            </nav>
        </header>

        {% block content %}{% endblock content %}
    </div>

    <!--Canvas sidebar  -->
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel">MENÚ</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="d-grid gap-2 mt-3">          
            {% if user.is_authenticated %}
            {% block sidebar-inbox %}
                <center>
                    <strong>Welcome:</strong>  <span class="text-success">{{user.get_username}}</span>
                    <br><br>
                </center>
                <a href="" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#logout-modal">Logout</a>
                <a href="{% url 'admin:index' %}" target="_blank" class="btn btn-outline-secondary btn-sm">Admin</a>
            {% endblock sidebar-inbox %}
            
            {% else %}
            {% block sidebar %}
            <a href="{% url 'login' %}" class="btn btn-success btn-sm">Login</a>
            {% endblock sidebar %}
            {% endif %}
            <hr><br>
            <center>
                <i class='bx bx-send bx-rotate-270' style="color: #e9e9e9; font-size: 150px;"></i>
            </center>
        </div>
    </div>
    </div>



    <!-- FOOTER -->
    <footer class="bg-dark text-center text-lg-start" id="footer">
        <div class="text-center p-3 text-light" style="background-color: rgba(0, 0, 0, 0.2);">
            &copy; {% now "Y" %} Copyright:
            <a href="#" class="text-decoration-none"">
                <span style="color: #8abaae;">www.pythoncode.com</span>
            </a>
        </div>
    </footer>

    
    {% block autologout %}
        <!-- Button to call logout warning -->
        <button id="warning" class="btn" data-bs-toggle="modal" data-bs-target="#warning-modal" style="display: none;"></button>

        <!-- AUTOLOGOUT BUTTON HIDDEN -->
        <a href="/auto_logout/" id="info" class="btn" style="display: none;"></a>
    {% endblock autologout %}
        

    <!-- ======= INCLUDES ======= -->
    {% include 'modals/logout.html' %}
    {% include 'modals/message.html' %}
    {% include 'modals/email.html' %}

    {% include 'modals/logout_warning.html' %}
    {% include 'modals/logout_info.html' %}



    <!-- SHOW MESSAGES FROM BACKEND -->
    {% if form.errors %}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script>
            swal("Acceso Denegado !", "Ingrese sus datos correctamente", "info")
        </script>
    {% endif %}

    <!-- messages from backend -->
    
    {% for message in messages %} 
        {% if message.tags == 'success' %}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script>
            let msg = "{{message}}"
            swal("Perfect !", msg, "success")
        </script>
        {% endif %}          
    {% endfor %}
        
    <!-- AUTO LOGOUT (home.html) -->
    {% for message in messages %} 
        {% if message.tags == 'info' %}
        <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
        <script>
            $(document).ready(function(){
                $('#info-modal').modal('show')
            })
        </script>

        {% endif %}          
    {% endfor %}
    
       
    <!-- Bootstrap Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Input mask -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.8-beta.17/jquery.inputmask.min.js" integrity="sha512-zdfH1XdRONkxXKLQxCI2Ak3c9wNymTiPh5cU4OsUavFDATDbUzLR+SYWWz0RkhDmBDT0gNSUe4xrQXx8D89JIQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Typed Js -->
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>

    <!-- Sweete alert -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!-- custom js -->
    <script src="{% static 'js/scripts.js' %}"></script>

    <!-- Typed effect control-->
    
    {% block typed %}
    <script>
        let typed = new Typed('#element', {
            strings: [
                'Somos una compañía de consultoría',
                'brindamos asesorias personalizadas',
                'con resultados eficientes e inmediatos'
            ],
            typedSpeed: 30,
            backSpeed: 30,
            loop: true
        })
    </script>
    {% endblock typed %}

    <script>
        
        // Function pulse the text (login page)  text intermitente
        (function pulse () {
            $('.text-pulse').fadeOut(1000).fadeIn(1000, pulse)
        }) ()

        // FUNCTION CLOSE OFFCANVAS WHEN BUTTON OF MODAL IS CLICKED
        jQuery('#offcanvasRight, .offcanvas-body a').click(function() {
            console.log($(this).attr('href'))
            jQuery('.offcanvas').offcanvas('hide')
        })

        // function to accept until 2mb al cargar un archivo
        let upload = document.getElementById('file')
        upload.onchange = function() {
            if(this.files[0].size > 2 * 1048576) {
                swal("Atención !", "El archivo no debe ser superior a 2mb.", "info")
                this.value = ''
            }
        }

        // AJAX FUNCTION LOAD SPINNER
        jQuery(function($){
            $(document).ajaxSend(function(){
                $('#bg-spinner').fadeIn(500)
            })

            $('.send-mail').click(function(){
                $.ajax({
                    type: 'GET',
                    success: function(data){
                        let d = $.parseJSON(data)
                        alert(d.Test)
                    }
                }).done(function() {
                    setTimeout(function(){
                        $('#bg-spinner'.fadeOut(500))
                    }, 700)
                })
            })
        })

        // CLOSE MODAL AFTER SEND BUTTON IS CLICKED
        $('.send-mail').click(function(){
            let msg = $('#email-msg').val()
            let subject = $('#email-subject').val()

            if((msg != '') && (subject != '')){
                $('.close-modal').modal('hide')
            }
        })
    </script>     
</body>
</html>

App/templates/customer.html
{% extends 'base.html' %}
{% block title %} customer {% endblock title %}
{% block datetime %}
    <div id="desk-datetime" class="text-light" style="margin-top: 5px;">
        <i class="bi bi-person-bounding-box" style="font-size: 20px;"></i>&nbsp;&nbsp;
        <span style="font-size: 16px;" class="">{{customer.name}}</span>
    </div>                    
{% endblock datetime %}

{% block content %}
<div class="container">
    <div class="card text-center mt-3">
        <div class="card-header">
            Recibido el {{customer.created_at | date:"d \d\e F \d\e Y"}} a las {{customer.created_at | date:'H:i'}}
        </div>
        <div class="card-body">
            <form action="/mark_message/" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{customer.id}}">
                <div class="input-group mb-2">
                    <span class="input-group-text justify-content-center side-label"><i class="bi bi-telephone-fill"></i></span>
                    <input class="form-control" id="input-bg" value="{{customer.phone}}" readonly>
                </div>

                <div class="input-group mb-2">
                    <span class="input-group-text justify-content-center side-label"><i class="bi bi-envelope-fill"></i></span>
                    <input class="form-control" id="input-bg" value="{{customer.email}}" readonly>
                </div>

                <div class="input-group mb-2">
                    <span class="input-group-text justify-content-center side-label"><i class="bi bi-briefcase-fill"></i></span>
                    <input class="form-control" id="input-bg" value="{{customer.subject}}" readonly>
                </div>

                <div class="form-group">
                    <textarea name="" id="input-bg" class="form-control" rows="10">{{customer.message}}</textarea>
                </div>

                <div class="input-group mb-3 mt-3">
                    <a href="/media/{{customer.file}}" class="bg-dark text-light input-group-text justify-content-center side-label text-decoration-none" target="_blank"
                    >
                        <i class="bi bi-paperclip"></i>
                    </a>
                    
                    {% if customer.file == '' %}
                    <input class="form-control" id="input-bg" value="Sin Archivos Adjuntos" readonly> 
                    {% else %}
                    <input class="form-control" id="input-bg" value="{{customer.file}}" readonly>
                    {% endif %} 
                </div>  

                <!-- Enviar el valor del status al bacjend -->
                
                {% if customer.status == 'Pending' %}
                    <input type="hidden" name="status" class="form-control" value="Read">                    
                {% endif %}
                    
                {% include 'modals/mark.html' %}
            </form>

            
            {% if customer.status == 'Pending' %}
            <a class="btn btn-dark" title="Volver" id="btn-back" data-bs-toggle="modal" data-bs-target="#mark-modal">
            {% else %}
            <a href="{% url 'main:inbox' %}" class="btn btn-dark" title="Volver" id="btn-back">
            {% endif %}
                <i class="bi bi-arrow-left"></i>
            </a>  


            <a class="btn text-light" title="Responder Email" id="reply" data-bs-toggle="modal" data-bs-target="#reply-modal">
                <i class="bi bi-reply-all-fill"></i>&nbsp;&nbsp; <span>Responder</span>
            </a>
        </div>
    </div>
</div>

<!-- AJAX SPINNER BACKEND -->
<div id="bg-spinner">
    <div id="position-spinner">
        <div class="d-flex justify-content-center">
            <div class="spinner-border text-success" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
</div>

<!-- SCRIPT PARA EVITAR LA ACCIÓN DEL RETROCESO DEL NAVEGADOR  Y USAR EL BACK DEL FORMULARIO -->
<!-- <script>
    history.pushState(null, null, null)
    window.addEventListener('popstate', function(){
        history.pushState(null, null, null)
    })
</script> -->
{% endblock content %}

App/templates/inbox.html
{% extends 'base.html' %}
{% block title %} inbox {% endblock title %}

<!-- Block image deleted -->
{% block bg-image %}{% endblock bg-image %}
{% block typed %}{% endblock typed %}


{% block datetime %}
    <div id="desk-datetime" class="text-light" style="font-size: 12px; margin-top: 5px;">
        {% now 'l (m-d-Y)' %} &nbsp;
        <span style="color: #8abaae; font-weight: bold;" id="clock"></span>
    </div>                    
{% endblock datetime %}

{% block content %}
<div class="container-fluid mt-3" style="width: 90%;">
    <!-- INFORMATION CARDS SECTION -->
    <div class="hide">
        {% include 'dashboard/dashboard.html' %}
    </div>
    <br>

    <!-- GLOBAL SEARCH -->
    <form action="" class="hide">
        <div class="input-group input-group-sm mb-3">
            <input class="form-control input-sm" type="text" name="q" placeholder="Search for..." value="{{request.GET.q}}">
            <button class="btn btn-secondary" title="Search">
                <i class="bi bi-search"></i>
            </button>
            <a href="{% url 'main:inbox' %}" class="btn btn-dark" title="refresh" style="margin-left: 3px;">
                <i class="bi bi-arrow-repeat"></i>
            </a>
        </div>
    </form>

    <!-- SECTION TABLE -->
    <div class="col-lg-12 hide">
        <div class="mt-3">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th style="width: 18%;">Nombre</th>
                        <th style="width: 13%;">Teléfono</th>
                        <th style="width: 18%;">Email</th>
                        <th style="width: 18%;">Asunto</th>
                        <th style="width: 15%;">Fecha</th>
                        <th style="width: 10%;">Estado</th>
                        <th style="width: 8%; text-align: center;" colspan="2">Acciones</th>
                    </tr>
                </thead>
                <!-- DATA FROM BACKEND -->
                <tbody>
                    
                    {% for c in customers %}       
                    <tr id="check_td" class="text-td">
                        <td id="top-table" label="Name">{{c.name}}</td>
                        <td id="responsive-border" label="Phone">{{c.phone}}</td>
                        <td id="responsive-border" label="Email">{{c.email}}</td>
                        <td id="responsive-border" label="Subject">{{c.subject}}</td>
                        <td id="responsive-border" label="Received on">{{c.created_at | date:'m-d-Y  (H:i'}}</td>
                        
                        {% if c.status == 'Pending' %}
                        <td id="responsive-border" label="Status" class="text-danger">{{c.status}}</td>
                        {% else %}
                        <td id="responsive-border" label="Status" >{{c.status}}</td>
                        {% endif %}
                        
                        <td>
                            <button class="btn btn-secondary btn-sm btn-action" title="Eliminar mensaje" data-bs-toggle="modal" data-bs-target="#delete-modal{{c.id}}">
                                <i class="bi bi-trash"></i>
                            </button>
                        </td>
                        <td>
                            <a href="{% url 'main:customer' c.id %}" class="btn text-light btn-sm btn-action" title="Leer mensaje" style="background-color: #2e856e;">
                                <i class="bi bi-envelope-at-fill"></i>
                            </a>
                        </td>
                    </tr>

                    <!-- MODAL DELETE CONFIRMATION -->
                    {% include 'modals/delete_message.html' %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
    <!-- ===========  PAGINATION ============== -->
    <nav class="hide">
        <ul class="pagination">
        {% if customers.has_previous %}
            <a href="?page=1" class="btn btn-outline-secondary mb-4" style="border-radius: 1px; border: 1px solid #d3d3d3;">
                First
            </a>
            <li class="page-item">
                <a class="page-link" href="?page={{ customers.previous_page_number }}"><i class="bi bi-chevron-double-left"></i></a>
            </li>
        {% endif %}
                
            <li class="page-item">
                <span class="page-link text-muted" style="border-radius: 1px; border: 1px solid #d3d3d3;">
                    Página {{ customers.number }} of {{ customers.paginator.num_pages }}.
                </span>
            </li>
                
        {% if customers.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{customers.next_page_number}}">
                    <i class="bi bi-chevron-double-right"></i>
                </a>
            </li>
            <a href="?page={{customers.paginator.num_pages}}" class="btn btn-outline-secondary mb-4" style="border-radius: 1px; border: 1px solid #d3d3d3;"
            >
                Last
            </a>
        {% endif %}
        </ul>
    </nav>  
</div>

<!-- SEARCH FAILED -->
<span class="text-danger" id="msg"></span>
<a href="{% url 'main:inbox' %}" id="refresh"></a>
{% endblock content %}



{% comment %}
    <nav>
        {% if customers.has_other_pages %}
        <ul class="pagination">
            {% if customers.has_previous %}
            <a href="?page=1" class="btn btn-outline-secondary mb-4" style="border-radius: 1px; border: ipx solid #d3d3d3;">First</a>
            <li class="page-item">
                <a class="page-link" href="?page={{ customers.previous_page_number }}"><i class="bi bi-chevron-double-left"></i></a>
            </li>
            {% else %}
            <li class="page-item disabled"></li>
            {% endif %}

            
            {% for i in customers.paginator.page_range %}
                
                {% if customers.number == i %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}<span class="sr-only"></span></span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                    </li>
                {% endif %}
                    
            {% endfor %}

            {% if customers.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{customers.next_page_number}}">
                    <i class="bi bi-chevron-double-right"></i>
                </a>
            </li>
            <a href="?page={{customers.paginator.num_pages}}" class="btn btn-outline-secondary mb-4" style="border-radius: 1px; border: ipx solid #d3d3d3;">
                Last
            </a>
            {% else %}
            <li class="page-item disabled"></li>
            {% endif %}     
        </ul>
        {% endif %}
    </nav>
{% endcomment %}


    